ARG BASE_IMAGE=ghcr.io/black-cloudlet/jetson-orin-bootc-microshift:latest
FROM ${BASE_IMAGE}

COPY services/manifests/ /etc/microshift/manifests.d/

ARG CERT_MANAGER_VER=v1.21.2
ARG KSERVE_VER=v0.20.0
RUN curl -fsSL \
      -o /etc/microshift/manifests.d/010-cert-manager/cert-manager.yaml \
      "https://github.com/cert-manager/cert-manager/releases/download/${CERT_MANAGER_VER}/cert-manager.yaml" && \

ARG SERVICE_IMAGES=""
RUN --mount=type=secret,id=pullsecret,dst=/run/secrets/pull-secret.json \
    images="$(/opt/microshift/manifest-images.sh \
        /etc/microshift/manifests.d/*/)" && \
    for img in ${images} ${SERVICE_IMAGES} ; do \
        /opt/physically-bound-images/embed_image.sh "${img}" \
            --authfile /run/secrets/pull-secret.json || exit 1 ; \
    done

RUN bootc container lint
